### ISSUE TITLE
StackOverflowError while using Levenstein scroe()

### ISSUE THREAD

**Issue by skuladeep24** [TeamCohen/secondstring#8]
We are facing an issue with the class below in a hadoop job. we are wondering if there are any limitations in using this class for calculating the similarity. Please advise.

Class: com.wcohen.ss.Levenstein

Method invocation:
Levenstein().score(str1, str2)

Error:
ERROR [main] org.apache.hadoop.mapred.YarnChild: Error running child : java.lang.StackOverflowError
	at com.wcohen.ss.MemoMatrix.get(MemoMatrix.java:40)
	at com.wcohen.ss.NeedlemanWunsch$MyMatrix.compute(NeedlemanWunsch.java:41)
	at com.wcohen.ss.MemoMatrix.get(MemoMatrix.java:40)
	at com.wcohen.ss.NeedlemanWunsch$MyMatrix.compute(NeedlemanWunsch.java:41)
	at com.wcohen.ss.MemoMatrix.get(MemoMatrix.java:40)
	at com.wcohen.ss.NeedlemanWunsch$MyMatrix.compute(NeedlemanWunsch.java:41)
	at com.wcohen.ss.MemoMatrix.get(MemoMatrix.java:40)
	at com.wcohen.ss.NeedlemanWunsch$MyMatrix.compute(NeedlemanWunsch.java:41)
	at com.wcohen.ss.MemoMatrix.get(MemoMatrix.java:40)
	at com.wcohen.ss.NeedlemanWunsch$MyMatrix.compute(NeedlemanWunsch.java:41)
	at com.wcohen.ss.MemoMatrix.get(MemoMatrix.java:40)
	at com.wcohen.ss.NeedlemanWunsch$MyMatrix.compute(NeedlemanWunsch.java:41)
	at com.wcohen.ss.MemoMatrix.get(MemoMatrix.java:40)
	at com.wcohen.ss.NeedlemanWunsch$MyMatrix.compute(NeedlemanWunsch.java:41)
	at com.wcohen.ss.MemoMatrix.get(MemoMatrix.java:40)
	at com.wcohen.ss.NeedlemanWunsch$MyMatrix.compute(NeedlemanWunsch.java:41)
	at com.wcohen.ss.MemoMatrix.get(MemoMatrix.java:40)
	at com.wcohen.ss.NeedlemanWunsch$MyMatrix.compute(NeedlemanWunsch.java:41)
	at com.wcohen.ss.MemoMatrix.get(MemoMatrix.java:40)
	at com.wcohen.ss.NeedlemanWunsch$MyMatrix.compute(NeedlemanWunsch.java:41)
	at com.wcohen.ss.MemoMatrix.get(MemoMatrix.java:40)
	at com.wcohen.ss.NeedlemanWunsch$MyMatrix.compute(NeedlemanWunsch.java:41)
	at com.wcohen.ss.MemoMatrix.get(MemoMatrix.java:40)
	at com.wcohen.ss.NeedlemanWunsch$MyMatrix.compute(NeedlemanWunsch.java:41)

**Comment by tfmorris** [comment]
You might want to look at the Apache implementation since its documentation specifically references usage with long strings https://commons.apache.org/proper/commons-text/apidocs/org/apache/commons/text/similarity/LevenshteinDistance.html
